Repository mighty-gerbils/gerbil, pull requests merged in 2023-10, with the labels that each got.

#964 Homebrew and MacOS fixes
  configure
  doc/guide/README.md
  doc/guide/macos.md
  homebrew/README.org
  homebrew/gerbil-scheme.rb
  src/build.sh
  src/build/build-bach.ss
  src/build/build-libgerbil.ss
  src/gerbil/compiler/driver.ss
  src/std/build-spec.ss
  src/std/os/signal-00-signalfd-test.ss
Labels: blocker

#982 recompile bootstrap for Gerbil v01.18-rc1
  src/bootstrap/gerbil/compiler/base__0.scm
  src/bootstrap/gerbil/compiler/compile.ssi
  src/bootstrap/gerbil/compiler/compile__0.scm
  src/bootstrap/gerbil/compiler/driver.ssi
  src/bootstrap/gerbil/compiler/driver.ssxi.ss
  src/bootstrap/gerbil/compiler/driver__0.scm
  src/bootstrap/gerbil/compiler/driver__1.scm
  src/bootstrap/gerbil/compiler/optimize-ann__0.scm
  src/bootstrap/gerbil/compiler/optimize-base__0.scm
  src/bootstrap/gerbil/compiler/optimize-call__0.scm
  src/bootstrap/gerbil/compiler/optimize-spec__0.scm
  src/bootstrap/gerbil/compiler/optimize-top__0.scm
  src/bootstrap/gerbil/compiler/optimize-xform__0.scm
  src/bootstrap/gerbil/compiler/optimize__0.scm
  src/bootstrap/gerbil/compiler/ssxi__1.scm
  src/bootstrap/gerbil/core.ssi
  src/bootstrap/gerbil/core__10.scm
  src/bootstrap/gerbil/core__11.scm
  src/bootstrap/gerbil/core__12.scm
  src/bootstrap/gerbil/core__13.scm
  src/bootstrap/gerbil/core__14.scm
  src/bootstrap/gerbil/core__15.scm
  src/bootstrap/gerbil/core__16.scm
  src/bootstrap/gerbil/core__2.scm
  src/bootstrap/gerbil/core__3.scm
  src/bootstrap/gerbil/core__4.scm
  src/bootstrap/gerbil/core__5.scm
  src/bootstrap/gerbil/core__6.scm
  src/bootstrap/gerbil/core__7.scm
  src/bootstrap/gerbil/core__8.scm
  src/bootstrap/gerbil/core__9.scm
  src/bootstrap/gerbil/expander/common__0.scm
  src/bootstrap/gerbil/expander/compile__0.scm
  src/bootstrap/gerbil/expander/core.ssi
  src/bootstrap/gerbil/expander/core.ssxi.ss
  src/bootstrap/gerbil/expander/core__0.scm
  src/bootstrap/gerbil/expander/module__0.scm
  src/bootstrap/gerbil/expander/root__0.scm
  src/bootstrap/gerbil/expander/stx__0.scm
  src/bootstrap/gerbil/expander/stxcase.ssi
  src/bootstrap/gerbil/expander/stxcase.ssxi.ss
  src/bootstrap/gerbil/expander/stxcase__0.scm
  src/bootstrap/gerbil/expander/top__0.scm
  src/bootstrap/gerbil/runtime/control__0.scm
  src/bootstrap/gerbil/runtime/error__0.scm
  src/bootstrap/gerbil/runtime/eval__0.scm
  src/bootstrap/gerbil/runtime/gambit__0.scm
  src/bootstrap/gerbil/runtime/init__0.scm
  src/bootstrap/gerbil/runtime/loader__0.scm
  src/bootstrap/gerbil/runtime/mop__0.scm
  src/bootstrap/gerbil/runtime/repl__0.scm
  src/bootstrap/gerbil/runtime/syntax__0.scm
  src/bootstrap/gerbil/runtime/system__0.scm
  src/bootstrap/gerbil/runtime/thread__0.scm
  src/bootstrap/gerbil/runtime/util__0.scm
  src/bootstrap/gerbil/runtime__0.scm
Labels: bootstrap

#981 Release v0.18 rc1
  .gitignore
  CHANGELOG.md
  doc/.vuepress/config.js
  src/gerbil/runtime/version.ss
Labels: release
